name: Markdown to PDF Conversion

on:
  workflow_dispatch:
    inputs:
      markdown:
        description: "Markdown content to convert to PDF"
        required: true
        type: string

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create public directory
        run: mkdir -p public

      - name: List directory contents
        run: ls -R

      - name: Convert Markdown to PDF
        run: |
          echo "${{ github.event.inputs.markdown }}" > input.md
          python convert.py input.md output.pdf

      - name: Move PDF to public directory
        run: cp output.pdf public/output.pdf

      - name: Commit and Push PDF
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/output.pdf
          git commit -m "Add generated PDF"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
